# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da6db83b63f2c842411ca38d4911e118186f053556fa051754cbfe224bdcca6ff6f00b4be508d5af53a934b1ceda4eb8babe80d5d1844e5841b42444b6ebe06d

test:
  secret_key_base: 1580d6c033e7be960628a9c32350ac979358e7da3ac71a9475e162731963d177c4800b747759995683222cda39c32722ca343406b187cf39fc2c377cfc2206af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
